INSERT INTO downtime (downtime_id, name) VALUES (1, 'Mechanical Downtime');
INSERT INTO downtime (downtime_id, name) VALUES (2, 'Electrical Downtime');
INSERT INTO downtime (downtime_id, name) VALUES (3, 'Operational Downtime');
INSERT INTO downtime (downtime_id, name) VALUES (4, 'Supplier Downtime');
INSERT INTO downtime (downtime_id, name) VALUES (5, 'HK Downtime');
INSERT INTO breakdown (breakdown_id, name) VALUES (1, 'Power Supply');
INSERT INTO breakdown (breakdown_id, name) VALUES (2, 'PLC/PCs');
INSERT INTO breakdown (breakdown_id, name) VALUES (3, 'Water Cooling Circuits');
INSERT INTO breakdown (breakdown_id, name) VALUES (4, 'Lubrication Grease, Gearbox Oil');
INSERT INTO breakdown (breakdown_id, name) VALUES (5, 'Sacrificial Grease (Tailskin, Shield Articulation, Main Drive, etc)');
INSERT INTO breakdown (breakdown_id, name) VALUES (6, 'Hydraulic Systems (Main, Auxiliary)');
INSERT INTO breakdown (breakdown_id, name) VALUES (7, 'Gripper functions (Main, Stabilizer)');
INSERT INTO breakdown (breakdown_id, name) VALUES (8, 'Roll Correction');
INSERT INTO breakdown (breakdown_id, name) VALUES (9, 'Thrust Cylinder (Main and Auxiliary)');
INSERT INTO shift_tbm_status (tbm_status_id, name) VALUES (1, 'Stoppage');
INSERT INTO shift_tbm_status (tbm_status_id, name) VALUES (2, 'Ring Build');
INSERT INTO shift_tbm_status (tbm_status_id, name) VALUES (3, 'Advance RB');
INSERT INTO shift_tbm_status (tbm_status_id, name) VALUES (4, 'Advance');
INSERT INTO shift_report_status (report_status_id, name) VALUES (1, 'draft');
INSERT INTO shift_report_status (report_status_id, name) VALUES (2, 'submitted');
INSERT INTO shift_report_status (report_status_id, name) VALUES (3, 'rejected');
